[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "nagato"
version = "0.0.1"
authors = [
    {name = "Takumi Nohara", email = "takumi.nohara.571@ctc-g.co.jp"},
]
description = "NAGATO: Network Automation Gears and Test Orchestrator"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = [
    "Framework :: Robot Framework",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "robotframework>=5.0.0",
    "netmiko>=4.0.0",
    "pysnmplib>=5.0.20",
    "ixnetwork-restpy>=1.1.10",
    "ntc-templates>=3.5.0"
]

[project.optional-dependencies]
dev = [
    "black",
    "ipython",
    "isort",
    "pytest"
]

[tool.setuptools.package-dir]
NetmikoLibrary = "packages/NAGATO/NetmikoLibrary"
NetworkUtils = "packages/NAGATO/NetworkUtils"
IxNetworkLibrary = "packages/NAGATO/IxNetworkLibrary"
Resources = "packages/NAGATO/Resources"
templates = "packages/NAGATO/templates"

[tool.isort]
profile = "black"
