name: libdoc

on:
  push:
    branches-ignore:
      - "master"
      - "develop"

jobs:
  generate:

    permissions:
      contents: write

    runs-on: "ubuntu-latest"

    env:
      PATH_TO_LIBRARIES: |
        src/NAGATO/IxNetworkLibrary
        src/NAGATO/NetmikoLibrary
        src/NAGATO/Resources/Cisco_IOS_XR.resource
        src/NAGATO/Resources/Juniper_Junos.resource
        src/NAGATO/PcapFileReader.py
        src/NAGATO/SNMP.py

    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Generate docs
        run: |
          git fetch --all
          for file in $PATH_FOR_LIBRARIES; do

            # Do not generate document if there are no differences from develop branch
            if git diff --exit-code --quiet origin/develop -- "$file"; then
              echo "No changes detected in $file"
              continue
            fi

            # Generate document
            echo "Generating document for $file"

            FILE_NAME=$(basename -- "$file")
            FILE_NAME_NO_EXT="${FILE_NAME%.*}"
 
            poetry run libdoc --name NAGATO.${FILE_NAME_NO_EXT} $file ./docs/${FILE_NAME_NO_EXT}.html
            git add ./docs/${FILE_NAME_NO_EXT}.html

          done

      - name: Push changes
        run: |
         if ! git diff --cached --exit-code; then
            git commit -m "Auto-generated commit by GitHub Actions"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
