name: libdoc

on:
  pull_request:
    branches:
      - master
      - develop
    types: [closed]

jobs:
  libdoc:

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    strategy:
      matrix:
        python-version: ["3.11"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    env:
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Create IxNetworkLibrary libdoc
        run: python3 -m robot.libdoc --name NAGATO.IxNetworkLibrary ./src/NAGATO/IxNetworkLibrary ./Docs/IxNetworkLibrary.html

      - name: Create NetmikoLibrary libdoc
        run: python3 -m robot.libdoc --name NAGATO.NetmikoLibrary ./src/NAGATO/NetmikoLibrary ./Docs/NetmikoLibrary.html

      - name: Create NetworkUtils libdoc
        run: python3 -m robot.libdoc --name NAGATO.NetworkUtils ./src/NAGATO/NetworkUtils ./Docs/NetworkUtils.html

      - name: Create Cisco_IOS_XR libdoc
        run: python3 -m robot.libdoc --name NAGATO.Cisco_IOS_XR ./src/NAGATO/Resources/Cisco_IOS_XR.resource ./Docs/Cisco_IOS_XR.html

      - name: Create Juniper_Junos libdoc
        run: python3 -m robot.libdoc --name NAGATO.Juniper_Junos ./src/NAGATO/Resources/Juniper_Junos.resource ./Docs/Juniper_Junos.html

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit & Push
        run: |
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit --author=. -m 'Update Libdoc.'
            git push
        if: steps.diff.outcome == 'failure'