name: nagato unittest

on:
  - push
  - pull_request

jobs:
  pytest_linux:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"] # TODO: Add 3.12
        platform: ["ubuntu-22.04"]

    runs-on: ${{ matrix.platform }}
    env:
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install tshark
        run: |
          sudo apt update
          sudo apt install -y tshark
          
      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest -m "not flaky" -v -s tests/

  pytest_win:
    strategy:
      matrix:
        python-version: ["3.11"]
        platform: ["windows-2022"]

    runs-on: ${{ matrix.platform }}
    env:
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install tshark
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install wireshark

      - name: Install dependencies
        run: poetry install
  
      - name: Run tests
        run: poetry run pytest -v -s tests/

