name: nagato unittest

on:
  - push
  - pull_request

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    env:
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install dependencies for dev
        run: python3 -m pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -v -s tests/
